spring:
  h2:
    console:
      enabled: true


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost
    username: root
    password: ${DB_PASSWORD}
server:
  port: 8080